---
title: "*Oxysternon festivum*"
subtitle: "Scarabaeinae"
bibliography: 
  - ../bibTeX/peer-review.bibtex
  - ../bibTeX/other.bibtex
  - ../bibTeX/reports.bibtex
nocite: |
  @Ferrer_Paris_2016
---

<p dir="ltr">En los estudios de monitoreo ambiental es necesario contar con indicadores que nos permitan cuantificar el estado del sistema de estudio. </p>
<p dir="ltr">Por ejemplo, si el estudio se enfoca en la biodiversidad de un sitio o regi&#243;n, debemos considerar tres propiedades fundamentales: estructura, composici&#243;n y funci&#243;n. Un muestreo a nivel de comunidades puede medir riqueza, equidad y diversidad&nbsp; (estructura), la diversidad beta o recambio de especies (composici&#243;n), y la diversidad funcional. </p>
<p dir="ltr">Sin embargo la repuesta de la comunidad de organismos es compleja y puede ser dif&#237;cil de interpretar. Un estudio directo de las poblaciones de especies seleccionadas puede ofrecer una medida m&#225;s directa del estado del sistema de estudio. Para ello es necesario comprender la respuesta funcional de una especie a los cambios en su entorno. </p>

<p dir="ltr">NeoMapas aporta datos de abundancia y distribuci&#243;n de varias especies que pueden servir como indicadores de la respuesta bi&#243;tica de la comunidad de invertebrados a la transformaci&#243;n del paisaje. Un ejemplo lo tenemos en el escarabajo <i>Oxysternon festivum</i> (Linn&#233; 1767), referido con el nombre vern&#225;culo de "Torococo vinotinto" por su vistosa coloraci&#243;n de un rojo cobrizo brillante. En un <a href="http://dx.doi.org/10.1007/s10841-016-9886-6">trabajo recientemente publicado</a> en la revista J<i>ournal of Insect Conservation </i>el grupo de trabajo de NeoMapas estudio a fondo las poblaciones de esta especie al sur del Orinoco. Este escarabajo se encuentra en los bosques del escudo Guayanes, usualmente acompa&#241;ado de una gran diversidad de otros escarabajos. Lo interesante de esta especie es su respuesta a los cambios ambientales: cuando otras especies m&#225;s sensibles desaparecen del bosque, el torococo vinotinto ocupa su lugar en la comunidad, lo que le permite incrementar su tama&#241;o y abundancia y de esta forma contribuir a mantener el funcionamiento del ecosistema ante la p&#233;rdida de diversidad. En otras palabras, la presencia de <i>O festivum</i> es una buena se&#241;al, pero una alta abundancia puede alertarnos sobre un desbalance en la composici&#243;n natural de especies, y sobe la necesidad de realizar acciones urgentes para preservar la integridad del bosque.</p>


# Documentos

::: {#refs}
:::