theme: jekyll-theme-minimal
title: "NeoMapas"
description: "Iniciativa para el Mapeo de la Biodiversidad Neotropical"
logo: "assets/images/logo_NeoMapas_p.gif"
show_downloads: "false"

collections:
  URA:
    output: true

defaults:
  - scope:
      path: ""
      type: "URA"
    values:
      layout: "ura"
  - scope:
      path: ""
    values:
      layout: "default"
