project:
  type: website
  output-dir: docs

website:
  title: "NeoMapas"
  repo-url: https://github.com/NeoMapas/NeoMapas.github.io
  repo-branch: alpha-centauri
  repo-actions: [edit, issue]
  favicon: /img/logo_NeoMapas_p.gif
  twitter-card: 
    creator: "@neomapas"
  site-url: https://neomapas.github.io
  margin-header: |
    ![Iniciativa para el monitoreo de la biodiversidad Neotropical](/img/logo_NeoMapas_p.gif)
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - referencias.qmd
      - personas.qmd
      - lugares.qmd
      - especies.qmd
      - about.qmd

format:
  html:
    theme: 
      light: united
      dark: superhero
    css: styles.css
    toc: true

lang: es

