project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!sandbox/"

execute:
  freeze: auto

website:
  title: "NeoMapas"
  repo-url: https://github.com/NeoMapas/NeoMapas.github.io
  repo-branch: alpha-centauri
  repo-actions: [edit, issue]
  favicon: /img/logo_NeoMapas_p.gif
  twitter-card: 
    creator: "@neomapas"
  site-url: https://neomapas.github.io
  margin-header: |
    ![Iniciativa para el monitoreo de la biodiversidad Neotropical](/img/logo_NeoMapas_p.gif)
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: "Lugares"
        menu:
          - text: "CNEB"
            href: CNEB.qmd
          - lugares.qmd
      - text: "Taxones"
        menu:
          - text: "Grupos indicadores"
            href: CNEB.qmd
          - text: "Mariposas"
            href: CNEB.qmd
          - text: "Escarabajos"
            href: CNEB.qmd
          - text: "Aves"
            href: CNEB.qmd
          - especies.qmd
      - referencias.qmd
      - personas.qmd
      - about.qmd

format:
  html:
    theme: 
      light: united
      dark: superhero
    css: styles.css
    toc: true

lang: es

