project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!sandbox/"

execute:
  freeze: auto

website:
  title: "NeoMapas"
  repo-url: https://github.com/NeoMapas/NeoMapas.github.io
  repo-branch: alpha-centauri
  repo-actions: [edit, issue]
  favicon: /img/logo_NeoMapas_p.gif
  twitter-card: 
    creator: "@neomapas"
  site-url: https://neomapas.github.io
  margin-header: |
    ![Iniciativa para el monitoreo de la biodiversidad Neotropical](/img/logo_NeoMapas_p.gif)
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: "Lugares"
        menu:
          - text: "CNEB"
            href: CNEB.qmd
          - lugares.qmd
      - text: "Taxones"
        menu:
          - text: "Grupos indicadores"
          - text: "Mariposas"
            href: CNEB.qmd
          - text: "Escarabajos"
            href: escarabajos.qmd
          - text: "Aves"
            href: aves.qmd
          - text: "Especies destacadas"
          - especies.qmd
      - text: "Producción científica"
        menu:
          - text: "Publicaciones"
            href: referencias.qmd
          - text: "Presentaciones"
            href: referencias.qmd
      - personas.qmd
      - about.qmd

bibliography: 
  - bibTeX/peer-review.bibtex
  - bibTeX/other.bibtex
  - bibTeX/reports.bibtex
  - bibTeX/preprints.bibtex
  - bibTeX/datasets.bibtex
  - bibTeX/other.bibtex

format:
  html:
    theme: 
      light: united
      dark: superhero
    css: styles.css
    toc: true

lang: es

