---
title: "Muestreo nacional de aves"
author: 
    - "JR Ferrer-Paris"
    - "AY Sánchez-Mercado"
    - "GA Rodríguez"
date: "21 Dec 2010"
---

## Sobre las Aves

<p>Las aves son los tetrápodos más diversos; sin embargo, tienen una gran homogeneidad morfológica en comparación con los mamíferos.</p>

<p>Las aves habitan en todos los biomas terrestres, y también en todos los océanos. El tamaño puede ser desde 6,4 cm hasta 2,74 metros. Los comportamientos son diversos y notables, como en la anidación, la alimentación de las crías, las migraciones, el apareamiento y la tendencia a la asociación en grupos. La comunicación entre las aves es variable y puede implicar señales visuales, llamadas y cantos. Algunas emiten gran diversidad de sonidos, y se destacan por su inteligencia y por la capacidad de transmisión cultural de conocimientos a nuevas generaciones.</p>


## Hábitat y distribución

<p>Las aves viven y crían en la mayoría de los hábitats terrestres y están presentes en todos los continentes. </p>

<p>La región biogeográfica con mayor número de especies, con unas 3.700 (más de la tercera parte mundial), es el Neotrópico (incluye América del Sur, América Central, tierras bajas de México y las Antillas). Además, 31 familias son endémicas del Neotrópico, más del doble que en cualquier otra región biogeográfica.</p>

## Importancia ecológica

<p>Uno de los roles más importantes de las aves es como polinizadores para las cual este grupo presenta adaptaciones importantes. Una de estas adaptaciones es la forma y tamaño de pico; algunas aves como los colibríes se alimentan del néctar de las flores y al tomar con su largo y estrecho pico el néctar se impregnan de polen que llevan de una flor a otra polinizándolas cada vez que se alimenta.</p>


<p>Otra manera en que las aves juegan un papel ecológico importante es como dispersoras de semillas, esto es, al ser tragadas las semillas por las aves, estas son depositadas en sitios donde podrán germinar y en otros casos las semillas deben pasar por el estomago de las aves para romper la capa mas externa que las cubre y así comenzar la germinación. Un ejemplo de lo anterior, lo constituyen los pericos que se alimentan de frutos o semillas en un sitio diferente a donde duermen transportando de esta manera dichas semillas a otros lugares o como los tucanes que se alimentan principalmente de frutas y que al volar las sueltan al defecar.</p>

<p>También se reconoce su importancia como controladores de plagas, desde insectos pequeños hasta ratones.</p>

<p>Finalmente, no hay que olvidar la importante labor de limpieza que desarrollan las aves carroñeras como los zamuros, quienes con su sistema inmunológico altamente desarrollado, al consumir los animales en descomposición así como algunos individuos enfermos mantienen la salud del ecosistema, evitando la presencia de enfermedades. Su cabeza desnuda impide contraer infecciones cuando se alimenta de las vísceras de los cadáveres.</p>


## Protocolos de muestreo de NeoMapas para Aves

### La unidad regional de análisis (URA): La transecta

<p>Consiste en una transecta de aproximadamente 40 km de longitud a lo largo de una carretera secundaria que pase por la gama más amplia posible de altitudes y tipos de vegetación dentro de la celda. A lo largo de cada transecta se realizaron  paradas de 3 minutos, con una distancia entre paradas de 0,8 km, lo que da un total de 50 paradas por transecta.</p>

### La unidad elemental de muestreo (UEM): conteo por puntos

<p>En cada parada, los conteos se realizan en una mañana (de 5 am a 12 m). En cada parada todos los individuos de todas las especies vistas u oídas fueron anotadas durante el lapso de tiempo correspondiente. Adicionalmente, realizamos grabaciones simultáneamente a los conteos.</p>


<p>El esfuerzo de muestreo de una transecta se mide por el total de minutos*observador (m*c) acumulados en todas los recorridos. </p>


