---
title: "Muestreo de escarabajos coprófagos"
author: 
    - "JR Ferrer-Paris"
    - "AY Sánchez-Mercado"
    - "C Lozano"
date: "21 Dec 2010"
---

# Sobre los escarabajos coprófagos

## Clasificación taxonómica

<p>Los escarabeínos (Scarabaeinae) son una subfamilia de coleópteros polífagos de la familia Scarabaeidae. La subfamilia se divide en 12 tribus con 234 géneros y más de 5.000 especies. </p>

<p>Sus principales distintivos biológicos son la asociación con el excremento y/o carroña de mamíferos y otros vertebrados, su especial modo de reproducción, así como las múltiples estrategias de aprovechamiento del excremento para su alimentación.</p>

<p>Aunque la mayoría de las especies son coprófagos, también existen algunas que consumen carroña, hongos, fruta podrida y otro material en descomposición. Los machos de algunas especies tienen grandes cuernos cefálicos y otras protuberancias de ornato sobre el pronoto.</p>


## Reproducción y desarrollo

<p>El escarabajo forma con sus patas posteriores, una bola (pelota) que alcanza hasta 10 veces su propio peso, le lleva pocos minutos formarla, para luego desplazarla rodándola, también con las paras posteriores aproximadamente doscientos metros, en busca de un terreno blando, para enterrar la bola, en la cual deposita sus huevos y de ella se alimenta en espera de que la temporada de lluvias retorne.</p>
 
<p>Durante la época de reproducción del escarabajo, el macho elabora una pelota más grande, aproximadamente 30 veces su propio peso, la cubre con sus feromonas para atraer a la hembra, cuando ésta acepta, se sube a la pelota y el macho la transporta a un terreno blando para enterrarla.</p>
 
<p>Una vez bajo tierra, se aparean y el macho parte en busca de otra hembra, la hembra ya fertilizada deposita sus huevos dentro de la esfera y cubre todo el exterior de la bola con su saliva para evitar su fermentación excesiva, que perjudicaría a las larvas, permanece cerca durante dos meses y finalmente se retira.</p>
 
<p>Una vez transcurrido el proceso deCNEB desarrollo, un nuevo escarabajo emergerá de la tierra para dar inicio a un nuevo ciclo, convirtiéndose de ese modo en el perfecto reciclador de la naturaleza.</p>

## Hábitat y distribución

<p>Los escarabajos coprófagos se encuentran en diversos hábitats, desde las tierras bajas tropicales, los desiertos y los bosques húmedos de mediana altitud, hasta los bosques templado-fríos de las partes más altas de las montañas y los pastizales alpinos. Muestran un amplio espectro alimentario (coprófilos, necrófilos, fitófagos, saprófagos, depredadores) aunque la mayoría son fitófagos y saprófagos, alimentándose de diversas partes de las plantas como raíces, hojas, flores, así como de materia vegetal y animal en descomposición (Halffter & Favila 1993; Estrada & Coates-Estrada 2002).</p>

## Importancia ecológica 

<p>La importancia de la comunidad de escarabajos coprófagos radica en que, mediante la dispersión de semillas y el reciclaje de nutrientes, mantienen la integridad del ecosistema; en sistemas agrícolas incrementan la productividad primaria y suprimen los parásitos del ganado.</p>

# Protocolos de muestreo de NeoMapas para escarabajos coprófagos

## La unidad regional de análisis (URA): La transecta

<p>Consiste en una transecta de aproximadamente 40 km de longitud a lo largo de una carretera secundaria que pase por la gama más amplia posible de altitudes y tipos de vegetación dentro de la celda. A lo largo de cada transecta se ubican diez grupos de seis u ocho trampas de caída, con una distancia entre grupos de trampas de 4 km, lo que da un total de 60 – 80 trampas por transecta. En cada grupo, las trampas deberán estar separadas por una distancia de 50 m y preferiblemente se repartirán en cantidades equitativas en cada lado de la carretera (e.g. si son 6 trampas, 3 de una lado y otras 3 del otro lado del a carretera).</p>

<p>El esfuerzo de muestreo de una transecta se mide por el total de horas*trampa (h*t) acumulados en todas las trampas. Para poder comparar dos o más transectas, es necesario que tengan un esfuerzo de muestreo similar.</p>

## La unidad elemental de muestreo (UEM): la trampa de caída cebada

<p>Las trampas de caída pueden construirse utilizando dos envases plásticos, uno de 13 cm diámetro y 13 cm de altura (840 ml de volumen aproximadamente) que sirve como molde y es enterrado a nivel del suelo. El otro envase, de 11 cm diámetro, 11 cm de altura (480 ml de volumen aproximadamente), será propiamente el envase de captura y se acopla y encaja al envase molde. Este segundo envase se llena con el líquido preservativo (ver más adelante). </p>

<p>Los envases están cubiertos por un techo para proteger la trampa del sol y la lluvia. El techo se hace con un plato plástico (51 cm de perímetro y 16,5 cm de diámetro) al cual se le insertan en cruz dos alambres (2 mm de diámetro y 53 cm de largo) que servirán como bases para enterrarlo sobre la trampa.</p>

<p>Los aspectos que deben tomarse en cuenta para el montaje de la trampas son los siguientes:

### Preparación de cebos

<p>Para preparar la carne en descomposición que se utilizará como cebo se colocan vísceras o partes de tejido en un envase plástico con tapa o en una cava pequeña de anime y se deja a la intemperie por cinco (5) días. Posteriormente, el tejido se tritura para crear una pasta. </p>

<p>Para preparar las heces humanas que se utilizarán como cebo se recolectan muestras de voluntarios en envases plásticos con tapa durante uno o dos días previos a la salida de campo con el fin de asegurar que se cuenta con suficiente cantidad, los envases son mantenidos en un tobo plástico con tapa o  en una cava con hielo, a fin de asegurar que se mantiene las propiedades organolépticas. Luego, en el momento de preparar los cebos, se combinan todas las muestras y se homogenizan en un único envase. </p>

<p>Para preparar los cebos, se colocan aproximadamente 20 grs de carroña o heces en una bolsa de tul de nylon y luego se amarra con una liga de goma para hacer pequeñas bolsas (Figura 2). Para manipular la carroña y las heces se puede utilizar cucharitas plásticas. El área donde se preparan los cebos debe estar alejada del sitio de muestreo para evitar interferencia. Es importante cubrir con papel periódico el piso del área donde se prepare el cebo y asegurarse de que todo el material sucio (envases, cucharitas, etc.) pueda recogerse luego con este papel. En la preparación de los cebos se recomienda el uso de tapa boca y guantes, así como el uso de mentol en la nariz para aminorar el efecto de los malos olores.</p>

### Montaje de las trampas

<p>Las trampas deben contener una solución de agua y etanol técnico (proporciones 40% y 60% respectivamente). La bolsa de tul que contiene el cebo es suspendida con un alambre corto. Para ello, se entierra el alambre en el suelo, de manera que el cebo quede suspendido por encima del líquido preservativo de los envases plásticos. </p>

<p>	El material requerido para instalar una trampa de caída incluye:
<ul><li>Un juego de trampas (cada trampa consiste en un envase de 480 ml uno de 220 ml, un plato plástico con alambres para soporte y un gancho de alambre para colgar una bolsa de tela con el cebo).
</li>
<li>Una planilla para cada trampa.</li>
<li>Una tabla de apoyo y un rapidografo.
</li>
<li>Cebos de diferentes tipos (heces, carne en descomposición, restos de insectos, fruta podrida, etc).
</li>
<li>Liquido preservador para colocar en las trampas.
</li>
<li>Un GPS.</li></ul>
</p>
</li>

### Revisión de las trampas

<p>El material debe ser colectado cada 24 horas por 3 días consecutivos (tiempos de revisión 24, 48 y 72 horas). No se realizan sustituciones de cebos durante todo el tiempo de muestreo a menos que éste haya sido robado. </p>

<p>Las capturas de cada día de cada trampa se separan en bolsas plásticas independientes y se rotulan la bolsas con marcador indeleble indicando fecha, transecta, punto de muestreo y número de trampa. Para mayor efectividad y rapidez de la colecta o revisión de trampas siga los siguientes pasos: 
<ul>
<li> Antes de abrir o utilizar la bolsa, se debe anotar con marcador indeleble el código de la trampa, código de la transecta, hora y fecha.</li>
<li> Pasar el líquido preservativo con los ejemplares por un colador, colocando otro envase plástico abajo debajo de forma que pueda reutilizarse el líquido en la trampa. Si es necesario se completa el líquido preservativo en la trampa.</li>
<li> Abrir la bolsa ya rotulada y colocar los ejemplares lavados, asegurarse que la bolsa queda bien cerrada.</li>
</ul>
</p>

<p>Las anotaciones de las condiciones de cada trampa deben realizarse en planillas específicas, para lo cual se asignará de forma exclusiva a uno de los integrantes del equipo. En la planilla se deben anotar aspectos tales como: presencia o ausencia de individuos, estatus del cebo, tipo de cebo reemplazado, estatus de la solución preservante, estatus del techo y la trampa en general o cualquier anormalidad observada en la trampa. Adicionalmente, se debe tomar nota del tipo de hábitat, así como de las principales perturbaciones (como quemas, deforestación, construcciones de viviendas, etc.).</p>

<p>Siempre que se revisen, instalen, activen o desactiven trampas, es necesario dejar anotado con fecha y hora todas estas condiciones en las planillas. Esto es particularmente importante cuando no se capturan individuos en las trampas, ya que posteriormente esto permitirá diferenciar si efectivamente no se capturaron ejemplares o si la bolsa de colecta se perdió o no se ha procesado.</p>

<p>El material requerido para revisar las trampas incluye:
<ul><li>Bolsas plásticas sencillas con etiquetas de papel.</li>
<li>Colador y un envase de 480 ml.</li>
<li>Etanol al 95% para colocar en las bolsas.</li>
<li>Liquido y cebos para reponer en las trampas.</li>
<li>Planillas y rapidografo.</li>
</ul>
</p>

</li>

### Procesamiento y limpieza del material

<p>Usualmente, la revisión de las trampas se hace en las mañanas, de manera que en las tardes se destina a limpiar y separar los escarabajos (no importa la familia) de cualquier otro organismo que haya caído en la trampa (hormigas, arañas, ranas, saltamontes, etc.). Los pasos para realizar esta limpieza son los siguientes:
<ol>
<li> Se deposita el contenido de una bolsa (muestra/trampa) en una bandeja y con una pinza se separan los escarabajos del resto de los organismos. De ser necesario se limpian con alcohol técnico utilizando una pisceta.</li>
<li>Los ejemplares de otros organismos se guardan en bolsas tipo ziplock rotuladas como “misceláneas”. Los ejemplares se agrupan por lotes de trampas (por ej., se junta el conteido de las 10 primeras trampas y se depositan en una sola bols), y se les coloca una etiqueta que indique transecta y grupo de trampas contenidas. Las arañas y arácnidos se separan de las “misceláneas” y se colocan en bolsas tipo ziplock, con una etiqueta réplica de la original. Se les agrega alcohol técnico a las bolsas. </li>
<li>Se cuentan los escarabajos y se anota el número en la planilla correspondiente a cada muestra/trampa.</li>
<li>Luego, se depositan los escarabajos en una bolsa con cierre clip (tipo ziplock) limpia y del tamaño adecuado a la cantidad de individuos. </li>
<li> Se replica la etiqueta original y se coloca una copia en la nueva bolsa. La etiqueta se escribirá lápiz a fin de evitar que el alcohol borre la tinta. </li>
<li>Se llena la bolsa de alcohol técnico y se cierra, procurando que no quede aire. </li>
<li>Se guardan las bolsitas procesadas en lotes (por grupos de trampas y juntando todos los días) en una bolsa ziplock más grande. Se agrega alcohol técnico a esta bolsa grande antes de cerrar y se saca el aire. </li>
<li>Las bolsas grandes se guardan en envases herméticos rotulados con el código de la transecta. Se agrega alcohol técnico al envase y se cierra.</li>
</ol>

<p>El material necesario para limpiar y separar el material incluye:
<ul>
<li>Bandejas de plástico o anime.</li>
<li>Pinzas y pinceles</li>
<li>Piscetas</li>
<li>Alcohol técnico (etanol 95%)</li>
<li>Toallín</li>
<li>Papel blanco para etiquetas</li>
<li>Tijeras</li>
<li>Rapidógrafos</li>
<li>Bolsas ziplock de diferentes tamaños</li>
<li>Envases herméticos</li>
<li>Planillas y rapidografo.</li>
<li>Una caja hermética para guardar las bolsas con las muestras limpias.</li>

</ul>
</p>
</li></ul></p>


<div class='referencias'>
<strong>Referencias</strong>

<p>Halffter, G. y Favila, M. E.. 1993. The Scarabaeinae (Insecta: Coleóptera) an animal group for analysing, inventorying and monitoring biodiversity in tropical rainforest and modified landscapes. Biol. Interna. No. 27. 21 pp.</p>

<p>Estrada, A. & R. Coates-Estrada.  2002.  Dung beetles in continuous forest, forest fragments and in an agricultural mosaic habitat-island at Los Tuxtlas, Mexico. Biodiversity and Conservation 11: 1903-1918.</p>
</div>

