---
title: "Narrativa de impacto"
lang: en
---

## Summary 

Tropical Latin America is home to an enormous share of the world's biodiversity. Despite its immense natural wealth, the region faces a significant deficit of reliable biodiversity data and lacks the local capacity necessary to collect such data. For more than 10 years, Dr José Rafael Ferrer-Paris has led the Neotropical Biodiversity Mapping Initiative (NeoMaps), a long-term biodiversity monitoring program. NeoMaps has not only addressed these gaps in biodiversity data in one of the megadiverse tropical countries, Venezuela, but has also emerged as a model for efficiently surveying biodiversity in developing countries while strengthening the local capacity needed to conduct these surveys. After three nationwide systematic surveys in 2006, 2009, and 2010, NeoMaps has compiled over 170,000 records of presence and abundance for birds, dung beetles, and butterflies. Additionally, it has provided the conceptual basis and practical skills required for designing and implementing biodiversity inventories to more than 60 conservationists from Venezuela, Colombia, Mexico, Peru, Bolivia, Brazil, Uruguay, and Spain. 

## Research description 

Tropical Latin America houses a significant portion of the world's biodiversity. Despite its immense natural wealth, the region faces a marked deficit in trained personnel and adequate funding for planning and prioritizing the conservation of its diverse species and ecosystems. 

The Neotropical Biodiversity Mapping Initiative (NeoMaps), led by Dr. José Rafael Ferrer-Paris, Ada Sánchez-Mercado, and Jon Paul Rodríguez, serves as a model for surveying biodiversity in developing countries, aiming to overcome the challenges of cost and time associated with large-scale surveys. 

NeoMaps minimizes the field effort required for generating biodiversity data by employing an environmentally stratified sampling design and applying spatial interpolation methods. This allows for the reliable and comparable collection of data in a country as vast as Venezuela (916,445 km2) within six months to a year. 

To achieve this, NeoMaps relies on field survey teams that bring together Venezuelan scientists and students with counterparts from neighbouring countries. For this purpose, three international postgraduate courses were held in 2006, 2009, and 2010 at the Ecology Centre of the Venezuelan Institute for Scientific Research. These theoretical and practical courses provided an ideal platform for uniting young individuals from different nationalities and areas of expertise, fostering the exchange of experiences and interactions with internationally recognized experts in biodiversity research. Students from Venezuela, Colombia, Mexico, Peru, Bolivia, Brazil, Uruguay, and Spain participated, alongside invited experts from the United States, Brazil, Costa Rica, Australia, and Venezuela. The students formed several working groups, and after a week of lectures and workshops, they embarked on expeditions to explore various regions of the country, conducting national inventories of dung beetles butterflies and birds. 

Between 2001 and 2005, an initial pilot phase was developed, followed by the establishment of uniform data collection protocols nationwide for birds, dung beetles, and butterflies in 2006. During these surveys, NeoMaps accumulated data across 25 locations visited throughout the country. They invested over 800 hours per person in butterfly collection and deployed over 140,000 hours per trap for beetle collection. This intensive effort resulted in the capture of more than 9,000 butterflies from XXX species and over 45,000 beetle specimens from >70 species. Additionally, NeoMaps recorded >170,000 bird observations. 


 

### Research impact 

#### Documenting changes in distribution 

Before NeoMaps, Venezuelan conservationists faced a significant challenge: the absence of comprehensive data on the abundance and distribution of species critical to their work. This information gap made it difficult to formulate effective strategies to protect threatened species and manage their habitats. 

NeoMaps emerged as a ground-breaking initiative, addressing this challenge head-on. By compiling data that spanned a wide range of vegetation types, climatic conditions, and landscape characteristics, NeoMaps became an invaluable resource for conservationists. It provided the tools needed to explore changes in the abundance and distribution of species, improve our knowledge about distribution for less know species, and allowing us to identify potential ecological indicator species to better understand responses of the biota to environmental changes. 

One notable impact of NeoMaps was its contribution to our understanding of parrot species' distribution and abundance. For instance, it identified that two widespread parrot species, Amazona amazonica and Amazona ochrocephala, initially considered of lesser concern, were experiencing a decline in their distribution. This discovery sent an alert throughout the conservation community. The data gathered by NeoMaps had the power to challenge established notions about the conservation status of certain species, highlighting the need of additional in-depth studies to uncover the meaning behind these contemporary absences. 

NeoMaps, also unveiled new information regarding the distribution of a dung-beetle species Oxysternon ebeninum. Its rigorous sampling efforts, allow identify new locations, each presenting unique temperature and precipitation range conditions previously unreported. These new sampling locations offered more than just geographical data; they provided crucial insights. NeoMaps' data revealed that not only biogeographic barriers, but ecological one played a significant role in shaping the distribution of this species. Thanks to this new information it becomes feasible to design sampling strategies aimed at advancing our comprehension of the species' ecology and biogeography in the future. 

Identifying a suitable ecological indicator is no small feat. It requires a species that not only lends itself to study but also offers profound insights into its ecological context. NeoMaps played a pivotal role in this endeavour by providing crucial occurrence and abundance data for the dung beetle Oxysternon festivum. It also supplied essential information about individual body size and total biomass, allowing us to assess its response to changing climatic conditions and vegetation cover. The results were promising. Oxysternon festivum demonstrated sensitivity to shifts in vegetation cover while exhibiting unexpected resilience. In hotter and drier regions, it not only thrived but also grew in abundance and size, potentially outcompeting more sensitive species. This remarkable adaptability positions Oxysternon festivum as a dynamic indicator species, offering valuable ecological insights. 

“This paper proposes a valuable procedure to defining the location of surveys in hyper diverse countries, also providing interesting results of the real capacities of such huge efforts to unveil "real" biodiversity data. In the reviewer’s opinion, which I concur with, the divulgation of this and similar approaches is very recommendable.” Dr Lluis Brotons, Associate Editor, Diversity and Distribution. 

#### Enhancing local capacities to monitoring biodiversity 

By combining the enthusiasm of young professionals with the consolidated knowledge of scientific experts, NeoMaps developed and strengthened regional capacity. 


> I enjoy seeing how students make the most of the opportunity to interact when speakers or researchers from other countries visit. They are very enthusiastic, coming from various countries: Uruguay, Bolivia, Peru, Colombia, Mexico, and Venezuela, each with their own country-specific issues. Some already have data, and when they have their own data, they are always interested in applying new techniques and seeing the results, especially because this has an impact on their work.
- Jonathan Coddington, Scientific Curator at the National Museum of the Smithsonian Institute, USA. 

 
NeoMaps had a direct impact on 60 conservationists across eight countries, including Venezuela, Colombia, Mexico, Peru, Bolivia, Brazil, Uruguay, and Spain. However, its impact extended beyond the participants, as NeoMaps provided data and mentorship opportunities for the future generation of researchers. Two postgraduate students developed their projects under Dr. Ferrer's supervision using NeoMaps' data. 

 For example, Dr. Cecilia Lozano assessed the conservation status of Venezuelan dung beetles during her postgraduate project at the Universidade Federal de Mato Grosso in Brazil. Dr. Arianna Thomas-Cabianca, currently the head of the Diptera section at the Senckenberg Natural History Collections in Germany, served as the curator of NeoMaps' dung beetle collection. Also, the interest for develop new sampling methods for butterflies and beetles of  Indiana Cristóbal Ríos-Málaver, currently Research Associate at the McGuire Center for Lepidoptera and Biodiversity in the University of Florida, emerged after NeoMaps course, as well as the passion for entomology of María Eugenia Lozada. For all of them, the early interactions with professionals from different countries were instrumental in expanding their vision of their roles in the conservation arena and creating the much-needed networking opportunities that were pivotal to advancing their international careers. 

> "They [course participants] may realize that conservation is not just a problem for scientists, such as biologists or ecologists, but it involves everyone who is around or works in the field of planning" Tatjana Good - James Cook University, Australia. 


### Selected media appearances 

 Scientists from IVIC (Venezuelan Institute for Scientific Research) are building a map of Neotropical biodiversity that crosses borders. Funvisis 29th August 2009  


