---
title: "Equipo de NeoMapas"
listing: 
  id: col-listing
  contents: personas
  type: grid
  fields: [image,  title]
  field-display-names:
    title: "Nombre"
---

::: {#col-listing}
:::

# Participantes, colaboradores y otros miembros del equipo de trabajo 

## Estudio piloto aves 2001-2002

Dr. Jon Paul Rodríguez, fundador de NeoMapas y proponente del protocolo de observación de aves

Chris Sharpe, proponente del protocolo de observación de aves y coordinador del estudio piloto

## Estudio piloto mariposas y escarabajos 2004-2005



*Expertos entomólogos*

Rafael Fernando Rey Cárdenas (†) contribuyó al muestreo de mariposas entre 2006 y 2009.

Antonio A. De Ascenção Da Silva (Universidad de Los Andes, Venezuela)

## Curso Internacional 2006

*Experto taxónomo invitado*

MSc. Ángel Solis, actualmente Curador de la colección de escarabajos del Museo Nacional de Costa Rica, identificó los especimenes de de escarabajos coprófagos y desarrollo las claves taxonómicas para la distinción de géneros, especies y morfotipos en Venezuela. 

*Asistentes de laboratorio*

Cecilia Lozano

## Curso Internacional 2009

**Coordinadores del Curso** 

José Rafael Ferrer-Paris y Ada Y. Sánchez-Mercado (IVIC) 

**Profesores componente teórico** 

- Tatjana Good, James Cook University (Australia)             
- Fernando  Vaz-de-Mello, Universidade Federal de Mato Grosso (Brasil)
- Ángel Solís, INBio (Costa Rica)
- Andrew Short, Universidad de Kansas (EEUU)      
- Jonathan Coddington, Smithsonian National Museum of Natural History  (EEUU)
- Ada Sánchez – Mercado, IVIC      
- Daniel Lew, Museo de Historia Natural La Salle
- Jafet Nassar, IVIC      
- Jesús Mavárez, IVIC
- José Clavijo, Museo del Instituto de Zoología Agrícola
- José Rafael Ferrer-Paris, IVIC      
- Laurie Fajardo, IVIC      
- Mariapia Bevilacqua, Fundación ACOANA

**Instructores de campo**

- Mery Córdova (Bolivia)
- Paola Cely (Colombia)
- Marianne Asmüssen (Chile)
- Douglas Mora (Venezuela)   
- Helios Martínez (Venezuela)     
- Mónica Núñez  (Venezuela) 

## Mantenimiento de la colección 2010-2018

Arlene Cardozo-Urdaneta

Arianna Thomas Cabianca

Helios Martínez

