---
title: "NM09 - Araya"
subtitle: "Sucre"
editor_options: 
  chunk_output_type: console
execute:
  echo: false 
  message: false
  warning: false
bibliography: 
  - ../bibTeX/datasets.bibtex
  - ../bibTeX/peer-review.bibtex
---

## Información básica

**NM**: 9

**CNEB**: d20

**Nombre**: Araya

**ADM1**: Sucre

**Estado_actual**: activa

**Responsables**: Pedro Borges :: Virginia Sanz

**Fecha**: 2003-09-21

**Informe**: Informes/NM09.pdf

**Resumen**: <p>Propuesta en 2003, inclu&iacute;da en el estudio piloto de mariposas y escarabajos en 2005, en los muestreos de mariposas de 2006 y los muestreos de mariposas y escarabajos en 2009. En 2005 presenciamos un movimiento masivo de mariposas (Junio), y en 2006 la abundancia de mariposas fue igualmente muy alta. La fauna de mariposas es relativamente rica considerando el clima semi&aacute;rido.</p>


## Ubicación

```{r}
#| label: Mapa
#| message: false
#| warning: false
require(sf)
library(dplyr)
library(tmap)
library(knitr)
library(readr)

gpstrack <- read_sf(here::here("sandbox","09.gpx"))
ruta <- gpstrack %>% filter(grepl("09", name)) %>% select(name) 
map1 <- tm_shape(ruta) + tm_symbols( col="orchid2") +tm_minimap()
tmap_leaflet(map1, show = FALSE, add.titles = FALSE)
```

Las coordenadas de los puntos de muestreo están disponibles en un repositorio en Dataverse [@NeoMapas_gpx].


## Actividades

- Estudio piloto mariposas y escarabajos [@FerrerParis_Calibracion_2006]
- Muestreo de mariposas en 2006, 2005, 2009 [@Ferrer_Paris_2012]
- Estudio piloto de muestreo de escarabajos en 2005 [@Ferrer_Paris_2013]
- Muestreo nacional de escarabajos en 2009 [@Ferrer_Paris_2012]
- Muestreo de aves en 2010 [@Rodr_guez_2012]


## Hallazgos importantes

Se observaron las siguientes especies del género Amazona: [*A. barbadensis*](/taxa/Amazona-barbadensis.qmd)  [@Amazona_pangaea_dataset].

En esta región se detecto la presencia de la [mariposas del Guayacán](/taxa/Kricogonia-lyside.qmd) *Kricogonia lyside*.