---
title: "NM13 - San Fernando"
subtitle: "Apure"
editor_options: 
  chunk_output_type: console
execute:
  echo: false 
  message: false
  warning: false
bibliography: 
  - ../bibTeX/datasets.bibtex
  - ../bibTeX/peer-review.bibtex
  - ../bibTeX/preprints.bibtex
  - ../bibTeX/other.bibtex
---

## Información básica

**NM**: 13

**CNEB**: i12

**Nombre**: San Fernando

**ADM1**: Apure

**Estado_actual**: activa

**Responsables**: Pedro Borges :: Yamil Madi

**Fecha**: 2003-10-28

**Informe**: Informes/13 San Fernando.xls

**Resumen**: <p>Sugerida en 2003 e inclu&iacute;da en muestreos de mariposas y escarabajos de 2006. En epoca de lluvia (mediados de a&ntilde;o) no es posible realizar esta transecta, por lo que se sugiere sustituirla por otro trazado o restringir los muestreos a un periodo del a&ntilde;o que garantice que la v&iacute;a sea accesible.</p>


## Ubicación

```{r}
#| label: Mapa
#| message: false
#| warning: false
require(sf)
library(dplyr)
library(tmap)
library(knitr)
library(readr)

gpstrack <- read_sf(here::here("sandbox","13.gpx"))
ruta <- gpstrack %>% filter(grepl("13", name)) %>% select(name) 
map1 <- tm_shape(ruta) + tm_symbols( col="orchid2") +tm_minimap()
tmap_leaflet(map1, show = FALSE, add.titles = FALSE)
```

Las coordenadas de los puntos de muestreo están disponibles en un repositorio en Dataverse [@NeoMapas_gpx].


## Actividades

- Muestreo de mariposas en 2006 [@Ferrer_Paris_2012]
- Estudio piloto de muestreo de escarabajos en 2006 [@Ferrer_Paris_2013]


## Hallazgos importantes


# Documentos

Publicaciones, conjuntos de datos y otros documentos que se refieren a esta unidad regional de análisis.

::: {#refs}
:::

