---
title: "NM26 - Jají"
subtitle: "Mérida"
categories:
 - Escarabajos 2005
 - Escarabajos 2009
editor_options: 
  chunk_output_type: console
execute:
  echo: false 
  message: false
  warning: false
---

## Información básica

**NM**: 26

**CNEB**: h04

**Nombre**: Jají

**ADM1**: Mérida

**Estado_actual**: activa

**Responsables**: Pedro Borges :: Yamil Madi

**Fecha**: 2003-05-12

**Informe**: Informes/26 Jaji.xls

**Resumen**: <p>Propuesta en 2003, inclu&iacute;da en el estudio piloto de mariposas y escarabajos en 2005, en los muestreos de mariposas de 2006 y los muestreos de mariposas y escarabajos en 2009. Incluye una peque&ntilde;a franja del Parque Nacional La Culata, donde se colectaron algunas especies interesantes de Leptophobia (Pieridae). Programada para NM Aves 2010.</p>


## Ubicación

```{r}
#| label: Mapa
#| message: false
#| warning: false
require(sf)
library(dplyr)
library(tmap)
library(knitr)
library(readr)

gpstrack <- read_sf(here::here("sandbox","26.gpx"))
ruta <- gpstrack %>% filter(grepl("26", name)) %>% select(name) 
map1 <- tm_shape(ruta) + tm_symbols( col="orchid2") +tm_minimap()
tmap_leaflet(map1, show = FALSE, add.titles = FALSE)
```

Las coordenadas de los puntos de muestreo están disponibles en un repositorio en Dataverse [@NeoMapas_gpx].


## Actividades

- Estudio piloto mariposas y escarabajos en 2005 [@FerrerParis_Calibracion_2006]
- Muestreo de mariposas en 2006, 2005, 2009 [@Ferrer_Paris_2012]
- Estudio piloto de muestreo de escarabajos en 2005 [@Ferrer_Paris_2013]
- Muestreo nacional de escarabajos en 2009 [@Ferrer_Paris_2012]
- Muestreo de aves en 2010 [@Rodr_guez_2012]


## Hallazgos importantes

En esta región se detecto la presencia de la mariposas endémica [*Ardaris eximia*](/taxa/Ardaris.qmd) [@LRFV_eximia]


# Documentos

Publicaciones, conjuntos de datos y otros documentos que se refieren a esta unidad regional de análisis.

::: {#refs}
:::

