---
title: "NM34 - Gavilán"
subtitle: "Amazonas"
editor_options: 
  chunk_output_type: console
execute:
  echo: false 
  message: false
  warning: false
bibliography: 
  - ../bibTeX/datasets.bibtex
  - ../bibTeX/peer-review.bibtex
  - ../bibTeX/preprints.bibtex
  - ../bibTeX/other.bibtex
---

## Información básica

**NM**: 34

**CNEB**: n12

**Nombre**: Gavilán

**ADM1**: Amazonas

**Estado_actual**: activa

**Responsables**: JR Ferrer Paris :: D Mora :: M Assmussen

**Fecha**: 2009-02-22

**Informe**: Informes/InformePreliminarTranseccion_NM34.pdf

**Resumen**: Propuesta en 2009, incluida en mariposas y escarabajos NM2009.


## Ubicación

```{r}
#| label: Mapa
#| message: false
#| warning: false
require(sf)
library(dplyr)
library(tmap)
library(knitr)
library(readr)

gpstrack <- read_sf(here::here("sandbox","34.gpx"))
ruta <- gpstrack %>% filter(grepl("34", name)) %>% select(name) 
map1 <- tm_shape(ruta) + tm_symbols( col="orchid2") +tm_minimap()
tmap_leaflet(map1, show = FALSE, add.titles = FALSE)
```

Las coordenadas de los puntos de muestreo están disponibles en un repositorio en Dataverse [@NeoMapas_gpx].


## Actividades

- Muestreo de mariposas en 2009 [@Ferrer_Paris_2012]
- Muestreo nacional de escarabajos en 2009 [@Ferrer_Paris_2012]
- Muestreo de aves en 2010 [@Rodr_guez_2012]


## Hallazgos importantes

Se observaron las siguientes especies del género Amazona: *A. amazonica*, *A. ochrocephala* [@Amazona_pangaea_dataset].

En esta región se detecto la presencia de una especie invasora de escarabajo coprófago [@Ferrer_Paris_digitonthophagus_2014].


# Documentos

Publicaciones, conjuntos de datos y otros documentos que se refieren a esta unidad regional de análisis.

::: {#refs}
:::

