---
title: "NM57 - Piñango"
subtitle: "Mérida"
categories:
 - Escarabajos 2009
editor_options: 
  chunk_output_type: console
execute:
  echo: false 
  message: false
  warning: false
---

## Información básica

**NM**: 57

**CNEB**: g05

**Nombre**: Piñango

**ADM1**: Mérida

**Estado_actual**: activa

**Responsables**: JR Ferrer Paris :: M Márquez :: D Mora :: P Colmenares

**Fecha**: 2009-05-16

**Informe**: Informes/InformePreliminarTranseccion_NM57.odt

**Resumen**: <p>Sugerida como alternativa a NM27 para incluir vegetaci&oacute;n de p&aacute;ramos pero en una carretera menos transitada. Incluida en muestreos de mariposas y escarabajos de 2009, programada para aves 2010.</p>


## Actividades

- Muestreo de mariposas en 2009 [@Ferrer_Paris_2012]
- Muestreo de aves en 2010 [@Rodr_guez_2012]


## Hallazgos importantes

En esta región se detecto la presencia de la mariposas endémica *Steromapedaliodes sanchezi*.

En esta región se detecto la presencia de la mariposas endémica [*Ardaris eximia*](/taxa/Ardaris.qmd) [@LRFV_eximia].


# Documentos

Publicaciones, conjuntos de datos y otros documentos que se refieren a esta unidad regional de análisis.

::: {#refs}
:::

